# Generated by Django 3.1.4 on 2020-12-13 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricebabaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricebaba',
            name='mobile',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(7000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
