# Generated by Django 3.1.4 on 2021-02-28 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricebabaapp', '0002_auto_20210228_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricebaba',
            name='created_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
